version: 1.2
workflows:
 - name: MycoSNP_Consensus_Assembly
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_mycosnp_consensus_assembly.wdl
   testParameterFiles:
    - empty.json
 - name: MycoSNP_Tree
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_mycosnp_tree.wdl
   testParameterFiles:
    - empty.json
