version: 1.2
workflows:
 - name: MycoSNP_Variants
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_mycosnp_variants.wdl
   testParameterFiles:
    - empty.json
 - name: MycoSNP_Tree
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_mycosnp_tree.wdl
   testParameterFiles:
    - empty.json
